### ISSUE TITLE
new feature: add tags with programmatically generated values such as time/date

### ISSUE THREAD

**Issue by olafmoriarty** [olafmoriarty/blue-bots-done-quick#13]
It should be possible to add tags such as {hour}, {month}, {date} or {phpdate [any php date string]} to include timestamps and stuff like that in the bot's code.

These should be processed before the tracery parser is run, so that one could e.g. write `#{month}#` and have the bot call the `#January#` trace.

For this to work properly, the user should be able to set their timezone in the bot's control panel.

**Comment by alien-sunset** [comment]
for clarity, would this allow us to set the bot to post from certain selections at certain times?

say I have a set of options for morning posts vs evening posts?
how would that work tracery code wise?

**Comment by olafmoriarty** [comment]
Tracery wise, since this would clearly not be vanilla tracery, I'm thinking it would make sense to use the curly brackets syntax. I'm thinking a logical format would be e.g. `{date string}` where `string` is a php date string – with aliases for common commands such as `{month}`, `{hour}` or `{weekday}` – and these would also work when used in tags. So you could write e.g. `It is {monthName}!`to return `It is November!`, or `I feel #mood{month}#`, which would be converted to `I feel #mood11#` which Tracery would then turn into `I feel gloomy`.
