### ISSUE TITLE
tracery breaks website.

### ISSUE THREAD

**Issue by alien-sunset** [olafmoriarty/blue-bots-done-quick#15]
I'm trying to add a new bot, and my code seems to be breaking the actual website itself.
https://bsky.app/profile/grandmas-quilt.bsky.social

if you can peak at my BBDQ for that bot, you can see all the code I can safely add and save.
that last svg text bit should be 

`"row1": [
"<text x='-7' y='40' fill='#color#' font-size='68'>#box#</text><text x='33' y='40' fill='#color#' font-size='68'>#box#</text><text x='73' y='40' fill='#color#' font-size='68'>#box#</text><text x='113' y='40' fill='#color#' font-size='68'>#box#</text><text x='153' y='40' fill='#color#' font-size='68'>#box#</text><text x='193' y='40' fill='#color#' font-size='68'>#box#</text><text x='233' y='40' fill='#color#' font-size='68'>#box#</text><text x='273' y='40' fill='#color#' font-size='68'>#box#</text><text x='313' y='40' fill='#color#' font-size='68'>#box#</text><text x='353' y='40' fill='#color#' font-size='68'>#box#</text>"
],`

but adding "#box#" breaks the entire web site and turns it into just a flat blue background

![image](https://github.com/user-attachments/assets/59cd20d5-20f4-47a2-9f06-bbd9a8a2291c)

(it appears to be the "x" in box that is the problem, as I can type "##" and "#bo#" with no issue, but as soon as I type the "x" the site goes blue.)

**Comment by olafmoriarty** [comment]
Should work now (refresh the page).

The preview component converts SVGs to Base64 to display them as images, and the function I was using to do that didn't support SVGs containing non-Latin characters.
