### ISSUE TITLE
Set image aspect ratio on upload

### ISSUE THREAD

**Issue by Perska** [olafmoriarty/blue-bots-done-quick#26]
Bluesky 1.95.0 made a change to the feed image displays, where if the post itself doesn't report an aspect ratio, it will be forcibly cropped to a square. (https://github.com/bluesky-social/social-app/pull/6474)

BBDQ doesn't appear to set this information at this time, leading images posted via it to be cropped.

Sample post (https://bsky.app/profile/blueybot.bsky.social/post/3lbxme2cnc32x)
![image](https://github.com/user-attachments/assets/8b203d68-8af0-45de-a632-02950a0d461c)

The aspect ratio is set with the `aspectRatio` property on an image embed, which itself consists of width and height. The official Bluesky client sets these to be the image's dimensions. (i.e. a 640x480 image would have its aspectRatio be `{width: 640, height: 480}`)

**Comment by olafmoriarty** [comment]
Whoops, I was not aware of that, thanks for the tip. Will of course fix this as soon as I can.
