### ISSUE TITLE
tags broken

### ISSUE THREAD

**Issue by alien-sunset** [olafmoriarty/blue-bots-done-quick#8]
the bot seems to be having difficulty with tags?

they show up fine in the little previews on blue bots, but are all janked up in the post:
![image](https://github.com/user-attachments/assets/700e7b87-1967-4787-b7ba-96c232a450d9)
![image](https://github.com/user-attachments/assets/2d5803a8-bfd6-4c77-bf1d-9a178e561eb3)

https://bsky.app/profile/remedios-varo-bot.bsky.social/post/3l7o2ytzjl32t

here's what it looks like in the code on blue bots, if there is some other way I should be formatting it, let me know.
![image](https://github.com/user-attachments/assets/d9a4c5c1-9ee9-4ef5-bdf6-6bcd01e12219)

**Comment by olafmoriarty** [comment]
Should be fixed now.
